funciones.h
Board* createBoard(int n, int m, Params params, code *statusCode)
References Board::n, Board::m, Board::matriz, NOT_ENOUGH_MEMORY, Ship::PosicionesTablero, Board::Enemigos, Board::BarcosEnemigos, Board::ActualBarcosEnemigos, Params::CantidadxTipoBarco, cfgShips, N, Ship::comandante, E, A, P, Ship::TipoAtaque, S, Ship::Largo, Board::Dificultad, Params::Dificultad, OK, Board::BarcosJugador, Board::ActualBarcosJugador, Board::JuegoFinalizado, WRONG_DIM.
Referenced by main, loadBoard.
void print(Board *b, int showComplete, code *statusCode)
References Board::n, Board::m, Board::matriz, OK, BOARD_NOT_FOUND.
Referenced by main.
int checkBoard(Board *b, code *statusCode)
References TRUE, FALSE, BOARD_NOT_FOUND, Board::m, Board::n, WRONG_DIM, Board::Dificultad, WRONG_DIFFICULTY, Board::BarcosEnemigos, IMPOSSIBLE_VALID_BOARD, OK.
Referenced by main.
void saveBoard(Board *b, int *id, code *statusCode)
References Board::n, Board::m, Board::Dificultad, ERROR_FILE_NOT_PERM, OK, BOARD_NOT_FOUND.
Referenced by main.
Board* loadBoard(int id, code *statusCode)
References setParams, createBoard, OK, ERROR_ID_NOT_FOUND, ERROR_FILE_NOT_PERM.
Referenced by main.
void putShip(Board *b, Position p, Ship s, code *statusCode)
References Ship::comandante, J, Ship::PosicionesTablero, Board::BarcosEnemigos, Board::BarcosJugador, Board::Jugador, Position::Fila, Board::n, Position::Columna, Board::m, Board::matriz, Ship::Largo, Ship::charBarco, Board::ActualBarcosJugador, OK, PUT_ERROR_OCUPPED, WRONG_DIM, ERROR_MAX_SHIP_REACHED, BOARD_NOT_FOUND.
Referenced by main.
int play(Board *b, Ship *ship, Position *pArray, code *statusCode)
References Board::UltimoJugador, Ship::comandante, Board::JuegoFinalizado, ERROR_GAME_FINALIZED, Position::Fila, Board::matriz, Position::Columna, N, A, P, S, B, J, BarcoAtacado, Board::Enemigos, Ship::Defensa, Ship::Vida, X, OK, Board::ActualBarcosEnemigos, O, E, Board::Jugador, Board::ActualBarcosJugador, W, WRONG_DIM, ERROR, ERROR_ITS_NOT_YOUR_TURN.
Referenced by main.
Position setPosition(int Fila, int Columna)
References Position::Fila, Position::Columna.
Referenced by main, AtaquesMasivos.
Ship cfgShips(int Largo, int Ancho, int ATKEspecial, char charBarco, int DEF)
References Ship::Largo, Ship::Ancho, Ship::Vida, Ship::TipoAtaque, Ship::charBarco, Ship::Defensa.
Referenced by main, createBoard.
int BarcoAtacado(Position p, Comandante comandante, Board *b)
References J, Board::BarcosEnemigos, Board::Enemigos, Ship::Largo, Ship::PosicionesTablero, Position::Fila, Position::Columna, E, Board::BarcosJugador, Board::Jugador.
Referenced by play.
int* generateID()
Referenced by main.
Params setParams(int Dificultad, code *statusCode)
References WRONG_DIFFICULTY, Params::Dificultad, Params::CantidadxTipoBarco.
Referenced by main, loadBoard.
Position* AtaquesMasivos(Ship s, Position p, Board *b)
References Board::n, Board::m, Ship::TipoAtaque, setPosition, Position::Fila, Position::Columna.
Referenced by main.
void destroyBoard(Board **b)
References Board::m, Board::matriz.
int getScore(Game g)
References Game::board, Board::BarcosJugador, Board::BarcosEnemigos, Board::ActualBarcosEnemigos, Board::Dificultad.