CC=gcc

Battleship: funciones_189714319_MaturanaGuerra.c Battleship_189714319_MaturanaGuerra.c

	$(CC) -o Battleship_189714319_MaturanaGuerra.exe Battleship_189714319_MaturanaGuerra.c funciones_189714319_MaturanaGuerra.c -I -Wall.